### ISSUE TITLE
TypeError: cannot serialize '_io.TextIOWrapper' while pickling conformer objects generated by HotBit

### ISSUE THREAD

**Issue by skrsna** [ReactionMechanismGenerator/AutoTST#46]
* Pickling `Conformer` objects generated by `HotBit` calculator leads to `TypeError: cannot serialize '_io.TextIOWrapper' ` error. Googling this error resulted in several posts stating that this is [unsolvable](https://nickp60.github.io/jekyll/python/blog/2016/11/12/gripes-about-multiprocessing.html) and inherent in `multiprocessing` and I don't know where I should look if I were to fix it. I'm just opening this issue to keep track of it.

**Comment by rwest** [comment]
What is the object you’re trying to serialize?
Some part of Conformer?

**Comment by rwest** [comment]
https://docs.python.org/3/library/pickle.html#pickling-class-instances

**Comment by skrsna** [comment]
I'm trying to pickle the whole `Conformer` object to update the Mongo Collection. Using EMT or DFTB calculators doesn't give this error though. But I'll look into how to solve this.

**Comment by rwest** [comment]
Try to figure out which part of the conformer object is causing the problem. Presumably some attached Calculator or something.

**Comment by skrsna** [comment]
Fixed this by remaking the `Conformer` objects using `_ase_molecule` attribute.
