### ISSUE TITLE
Suggestion to increment cclib version

### ISSUE THREAD

**Issue by alongd** [ReactionMechanismGenerator/AutoTST#88]
## Describe the bug
AutoTST uses [cclib == v.1.6.2](https://github.com/ReactionMechanismGenerator/AutoTST/blob/master/environment.yml#L15) which [does not support](https://github.com/cclib/cclib/blob/release-1.6.2/cclib/io/filewriter.py#L29) the new openbabel >= 3.0 import syntax. A new environment made recently for AutoTST contains `cclib                     1.6.2` and `openbabel                 3.1.1`, leading to a crash when [cclib is called](https://github.com/ReactionMechanismGenerator/AutoTST/blob/master/autotst/data/base.py#L40) and tries to import OB. The most recent release of cclib (1.7) [does import OB >= 3.0 correctly](https://github.com/cclib/cclib/blob/release-1.7/cclib/io/filewriter.py#L23).

## How to reproduce the bug
Create a new tst_env and run AutoTST. 

## Expected behavior
For the libraries to not collide. The root problem is probably that AutoTST requires cclib to be **exactly** v. 1.6.2, while this version of cclib does not cap the version of OB to <= 3.0, leading to a collision.

**Additional context**
I don't know whether cclib **v. 1.6.2** is a hard requirement in AutoTST, if it's not, I'd suggest changing to `cclib >= 1.7`

**Comment by rwest** [comment]
I assume this is closed by #89
